system 'rails destroy controller UserIncomings'
system 'rails destroy controller UserOutgoings'
system 'rails destroy controller UserNotes'
system 'rails destroy controller UserExecutions'
system 'rails destroy scaffold UserInternal'
