require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncomingsController do

  # This should return the minimal set of attributes required to create a valid
  # Incoming. As you add validations to Incoming, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncomingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all incomings as @incomings" do
      incoming = Incoming.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incomings).should eq([incoming])
    end
  end

  describe "GET show" do
    it "assigns the requested incoming as @incoming" do
      incoming = Incoming.create! valid_attributes
      get :show, {:id => incoming.to_param}, valid_session
      assigns(:incoming).should eq(incoming)
    end
  end

  describe "GET new" do
    it "assigns a new incoming as @incoming" do
      get :new, {}, valid_session
      assigns(:incoming).should be_a_new(Incoming)
    end
  end

  describe "GET edit" do
    it "assigns the requested incoming as @incoming" do
      incoming = Incoming.create! valid_attributes
      get :edit, {:id => incoming.to_param}, valid_session
      assigns(:incoming).should eq(incoming)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incoming" do
        expect {
          post :create, {:incoming => valid_attributes}, valid_session
        }.to change(Incoming, :count).by(1)
      end

      it "assigns a newly created incoming as @incoming" do
        post :create, {:incoming => valid_attributes}, valid_session
        assigns(:incoming).should be_a(Incoming)
        assigns(:incoming).should be_persisted
      end

      it "redirects to the created incoming" do
        post :create, {:incoming => valid_attributes}, valid_session
        response.should redirect_to(Incoming.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incoming as @incoming" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incoming.any_instance.stub(:save).and_return(false)
        post :create, {:incoming => {}}, valid_session
        assigns(:incoming).should be_a_new(Incoming)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incoming.any_instance.stub(:save).and_return(false)
        post :create, {:incoming => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incoming" do
        incoming = Incoming.create! valid_attributes
        # Assuming there are no other incomings in the database, this
        # specifies that the Incoming created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incoming.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => incoming.to_param, :incoming => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested incoming as @incoming" do
        incoming = Incoming.create! valid_attributes
        put :update, {:id => incoming.to_param, :incoming => valid_attributes}, valid_session
        assigns(:incoming).should eq(incoming)
      end

      it "redirects to the incoming" do
        incoming = Incoming.create! valid_attributes
        put :update, {:id => incoming.to_param, :incoming => valid_attributes}, valid_session
        response.should redirect_to(incoming)
      end
    end

    describe "with invalid params" do
      it "assigns the incoming as @incoming" do
        incoming = Incoming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incoming.any_instance.stub(:save).and_return(false)
        put :update, {:id => incoming.to_param, :incoming => {}}, valid_session
        assigns(:incoming).should eq(incoming)
      end

      it "re-renders the 'edit' template" do
        incoming = Incoming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incoming.any_instance.stub(:save).and_return(false)
        put :update, {:id => incoming.to_param, :incoming => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incoming" do
      incoming = Incoming.create! valid_attributes
      expect {
        delete :destroy, {:id => incoming.to_param}, valid_session
      }.to change(Incoming, :count).by(-1)
    end

    it "redirects to the incomings list" do
      incoming = Incoming.create! valid_attributes
      delete :destroy, {:id => incoming.to_param}, valid_session
      response.should redirect_to(incomings_url)
    end
  end

end
