require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OutgoingsController do

  # This should return the minimal set of attributes required to create a valid
  # Outgoing. As you add validations to Outgoing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OutgoingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all outgoings as @outgoings" do
      outgoing = Outgoing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:outgoings).should eq([outgoing])
    end
  end

  describe "GET show" do
    it "assigns the requested outgoing as @outgoing" do
      outgoing = Outgoing.create! valid_attributes
      get :show, {:id => outgoing.to_param}, valid_session
      assigns(:outgoing).should eq(outgoing)
    end
  end

  describe "GET new" do
    it "assigns a new outgoing as @outgoing" do
      get :new, {}, valid_session
      assigns(:outgoing).should be_a_new(Outgoing)
    end
  end

  describe "GET edit" do
    it "assigns the requested outgoing as @outgoing" do
      outgoing = Outgoing.create! valid_attributes
      get :edit, {:id => outgoing.to_param}, valid_session
      assigns(:outgoing).should eq(outgoing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Outgoing" do
        expect {
          post :create, {:outgoing => valid_attributes}, valid_session
        }.to change(Outgoing, :count).by(1)
      end

      it "assigns a newly created outgoing as @outgoing" do
        post :create, {:outgoing => valid_attributes}, valid_session
        assigns(:outgoing).should be_a(Outgoing)
        assigns(:outgoing).should be_persisted
      end

      it "redirects to the created outgoing" do
        post :create, {:outgoing => valid_attributes}, valid_session
        response.should redirect_to(Outgoing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved outgoing as @outgoing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Outgoing.any_instance.stub(:save).and_return(false)
        post :create, {:outgoing => {}}, valid_session
        assigns(:outgoing).should be_a_new(Outgoing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Outgoing.any_instance.stub(:save).and_return(false)
        post :create, {:outgoing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested outgoing" do
        outgoing = Outgoing.create! valid_attributes
        # Assuming there are no other outgoings in the database, this
        # specifies that the Outgoing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Outgoing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => outgoing.to_param, :outgoing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested outgoing as @outgoing" do
        outgoing = Outgoing.create! valid_attributes
        put :update, {:id => outgoing.to_param, :outgoing => valid_attributes}, valid_session
        assigns(:outgoing).should eq(outgoing)
      end

      it "redirects to the outgoing" do
        outgoing = Outgoing.create! valid_attributes
        put :update, {:id => outgoing.to_param, :outgoing => valid_attributes}, valid_session
        response.should redirect_to(outgoing)
      end
    end

    describe "with invalid params" do
      it "assigns the outgoing as @outgoing" do
        outgoing = Outgoing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Outgoing.any_instance.stub(:save).and_return(false)
        put :update, {:id => outgoing.to_param, :outgoing => {}}, valid_session
        assigns(:outgoing).should eq(outgoing)
      end

      it "re-renders the 'edit' template" do
        outgoing = Outgoing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Outgoing.any_instance.stub(:save).and_return(false)
        put :update, {:id => outgoing.to_param, :outgoing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested outgoing" do
      outgoing = Outgoing.create! valid_attributes
      expect {
        delete :destroy, {:id => outgoing.to_param}, valid_session
      }.to change(Outgoing, :count).by(-1)
    end

    it "redirects to the outgoings list" do
      outgoing = Outgoing.create! valid_attributes
      delete :destroy, {:id => outgoing.to_param}, valid_session
      response.should redirect_to(outgoings_url)
    end
  end

end
